os:
  edit: 'lazygit-edit {{filename}}'
  editAtLine: 'lazygit-edit {{filename}} {{line}}'

customCommands:
  - key: 'K'
    context: 'files, commitFiles'
    description: 'Open in Kakoune split'
    prompts:
      - type: 'menu'
        title: 'Split direction'
        key: 'SplitDirection'
        options:
          - name: 'vertical'
            description: 'Create a left/right tmux split'
            value: 'h'
          - name: 'horizontal'
            description: 'Create a top/bottom tmux split'
            value: 'v'
    command: 'lazygit-edit {{.SelectedFile.Name | quote}} "" {{.Form.SplitDirection}}'
    output: terminal
gui:
  nerdFontsVersion: '3'
  showFileIcons: true

